- name: functions
  hosts: localhost
  connection: local
  become: yes
  vars:
    technologies: Devops, AWS, Linux, Ansible # It is string
    # Dictnoary/Maps
    tags:
      Application: Payment
      Environment: Dev
    # Lists
    listtags:
      - key: Dharanidhar
        Value: Payment
      - key: Environment
        Value: Dev
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Dharanidhar') }}" 
      # Here we didnot define any variable but we are calling it. if we assign any variable it will take it
      # Otherwise it will pick it from default function in this case we didn't assign variable it is taking from default.
 
 # Convert string to lists
  - name: convert string to lists
    ansible.builtin.debug:                           
      msg: "Technologies are {{ technologies | split(',') }}" 
      #"msg": "Technologies are Devops, AWS, Linux, Ansible" if we didn't use any functions/filters.
      #"msg": "Technologies are ['Devops', ' AWS', ' Linux', ' Ansible']" After applying split filter it became string to lists.

  # Convert Maps to lists
  - name: convert maps/Dictnoary to lists
    ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }}"
      #"msg": "Tags are: {'Application': 'Payment', 'Environment': 'Dev'}" ==> Before
      #"msg": "Tags are: [{'key': 'Application', 'value': 'Payment'}, {'key': 'Environment', 'value': 'Dev'}]" ==> After

  # Convert lists into Maps/Dictnoary
  - name: convert lists into Maps
    ansible.builtin.debug:
     msg: "Maps are {{ listtags | items2dict }}"
     #"msg": "Maps are [{'key': 'Dharanidhar', 'Value': 'Payment'}, {'key': 'Environment', 'Value': 'Dev'}]"   ==> Before
