- name: loops
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}" # item is the reserved word we use it as default keyword for calling variables in loop.
    loop:                     # In loops "loop" is the keyword
    - Dharanidhar
    - Swetha