- name: variables from files
  hosts: localhost
  connection: local
  vars_files:
    course.yaml
  tasks:
  - name: calling variables from file
    ansible.builtin.debug:
      msg: "Course name: {{ course }},Duration is: {{ duration }}, Tuitor is {{ tuitor }}"