- name: vars from inventory
  hosts: localhost
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "course : {{ course }}, Duration: {{ duration }}, tuitor is : {{ tuitor }}"